# Generated by Django 3.1.5 on 2022-11-10 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='assetId',
        ),
        migrations.RemoveField(
            model_name='media',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fileSize',
        ),
        migrations.RemoveField(
            model_name='media',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='media',
            name='height',
        ),
        migrations.RemoveField(
            model_name='media',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='media',
            name='width',
        ),
        migrations.AddField(
            model_name='media',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='media_data',
            field=models.ImageField(default=None, upload_to='media'),
            preserve_default=False,
        ),
    ]
